### ISSUE TITLE
Optionally support Type sorting

### ISSUE THREAD

**Issue by mattddean** [origami-z/TypeScript-Interface-Sorter#13]
Love this extension! Would be really neat if it could also sort TypeScript `Type`s the same way it sorts `Interface`s when a `tsInterfaceSorter.sortTypes` (or something like that) setting is set.

**Comment by origami-z** [comment]
Not sure how to best implement this yet. It's easy to modify the parser to recognise `type`, but don't want cheat the sorter by telling it they are also interfaces. Needs to do a bunch of rename and refactor.

**Comment by origami-z** [comment]
Released in v0.3.0
